# Generated by Django 5.2.8 on 2025-11-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('progress', models.FloatField(help_text='0.0 to 1.0')),
                ('schools_impacted', models.IntegerField()),
                ('students_impacted', models.IntegerField()),
                ('scholarships_awarded', models.IntegerField()),
                ('budget_utilized', models.FloatField(help_text='Crores')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='dashboard.scheme')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='dashboard.state')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='dashboard_i_year_4eb476_idx'), models.Index(fields=['category'], name='dashboard_i_categor_4f3112_idx'), models.Index(fields=['status'], name='dashboard_i_status_6397c2_idx')],
            },
        ),
    ]
