# Generated by Django 4.2.5 on 2025-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.SlugField(max_length=64, unique=True)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='dashboard_r_created_6822f5_idx'), models.Index(fields=['status'], name='dashboard_r_status_6e311f_idx')],
            },
        ),
    ]
